name: Build

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8.0.372+7
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B install --file pom.xml
      - name: Coveralls
        run: mvn -B coveralls:report --define repoToken=${{ secrets.MY_SECRET }}
